name: Pull Request
on:
  pull_request:
    types: [opened reopened syncronize]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v1
      - name: Lint code
        run: npm run lint:eslint
      - name: Lint styles
        run: npm run lint:stylelint
      - name: Check formatting
        run: npm run prettier:check
