name: Release
on:
  push:
    branches:
      - master
jobs:
  pages:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint:eslint
      - name: Lint styles
        run: npm run lint:stylelint
      - name: Check formatting
        run: npm run prettier:check
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          folder: out
          branch: gh-pages
          single-commit: true
          clean: true
          clean-exclude: CNAME
